CXX = g++
CXXFLAGS = -std=c++17 -pthread -Wall

SRC = logger.cpp manager.cpp worker.cpp raft/raft_node.cpp
OBJ = $(SRC:.cpp=.o)

all: manager worker

manager: manager.cpp logger.cpp raft/raft_node.cpp
	$(CXX) $(CXXFLAGS) -o manager manager.cpp logger.cpp raft/raft_node.cpp

worker: worker.cpp logger.cpp
	$(CXX) $(CXXFLAGS) -o worker worker.cpp logger.cpp

clean:
	rm -f manager worker *.o raft/*.o *.log state/*.json